### ISSUE TITLE
new algorithms.md feedback

### ISSUE THREAD

**Issue by rmarren1** [neurodata/checklists#39]
The only part I disliked was repeating the data simulation generation and plotting 10 times in steps 10 and 11 in the Simulation Analysis. The simulation data is often high dimensional and multiple plots are needed to show correctness, which results in the need for (in my case) 40+ high dimensional plots which take up a lot of space on Github (30+ megabytes), eat up a lot of RAM making the notebooks difficult to work in, and force people to scroll a lot in the notebook. I think that plotting a histogram of the 'metric' defined in Simulation Analysis step 7, and verbally reporting whether the qualitative plots on repeat trials appeared similar to the original could achieve the same goal.

Overall I think the blocked structure is better than the linear structure in the previous algorithms.md. The only deviation I found myself making was creating a new preceding section where I described at a high level the assumptions, guarantees, and basic theoretical properties of the algorithm which helped collect thoughts about what distributions should work well and which would fail. I don't know how others would feel about adding work, but I found that this step saved me time because I was more confident in my choices in distributions and didn't have to backtrack and change them.

**Comment by jovo** [comment]
@rmarren1 updated to address your comments.  if you think there is a better way to address them, please let me know.

**Comment by 02agarwalt** [comment]
I strongly prefer the current algorithms.md over the original code.md. I like the structuring because we can see how each section/step builds on the previous one. The core ideas behind algorithms.md don't take long (coming up with simulations, metrics, understanding the algorithms, etc.), but there are always a ton of little tedious details that come into play when actually implementing any simulations, getting the algorithms/tools to run, or deploying the algorithms on real data (maybe that's just me. Can anyone else confirm or deny?). The real data analysis further increases the time spent significantly because doing discriminability is often not straightforward. For this reason, I think we should increase the time commitment assumption from 10 hours to 15 hours (at least). I agree with Ryan that plotting ALL simulations is not viable all the time. Overall, I like the state of algorithms.md right now.

**Comment by jovo** [comment]
@02agarwalt thanks.  i think once we get the hang of discriminability for real data, it should go a bit faster.  but yes, in general, running things on real data takes some time.  i find i almost learn things about my code in the process, so it is very useful time.

**Comment by nkumarcc** [comment]
I personally liked both algorithm.mds, I think the first one's real weakness was that during the school year it took 2 weeks for me to complete for an algorithm (at least). As Eric pointed out near the end of the semester, it made sense to split it over 2 weeks. I legitimately spend at least 6 hours typically trying to understand the in-and-outs of the algorithm (notes taking + reading paper(s)) which I do think helps (I spent less for Kernel Density Estimation and that went to trash the first time I tried it). In addition I wholeheartedly agree with Tanay; implementation always has tedious points and complications that arise, and real data implementation takes time as well. That being said, I really appreciate the structure and the system and wholeheartedly support the methodology, I just think it should be definitely be expected to be 15 hrs - 20 hrs (1 week is manageable during intersession but semester will definitely be harder). Splitting it up or separating it somehow (one week dedicated to LaTeX, notes, pseudo, and real datasets, second week implementation and analysis?) I think is really the best idea so we can really do a thorough job with each part.

**Comment by bstadt** [comment]
My suggestions for Algorithms.md:

I think that the initial confusion about strict formatting arose because the example iPython notebook and the algorithms.md checklist are not strictly of the same format. In fact, they are actually very far from the same. If it was your intention to make algoritoms.md formatting very standardized, I think you would benefit from having the example notebook follow the formatting to a T.

With this being said, I think it may not be the best idea to create a strict format for evaluating algorithms. I don't believe that there is a "one size fits all" method for determining whether one algorithm is better than another or not.  For instance, I believe that there are circumstances where qualitative visualizations or quantitative numerics alone convey a point well enough not to warrant the use of the other. In fact, in some of these cases, providing both statistics and visualizations may even be confusing.

In terms of content, the analysis feels somewhat long-winded. I understand that the idea is to perform a thorough analysis; however, sections of the checklist (e.g. describe in words how you think the algorithm will perform...) are repeated multiple times, which gives the assignment the feel of busy work more than analysis.  

Also, I found that motivating some of my team to continue on with the analysis after the algorithm was known to be ineffective for our circumstance was quite difficult. Specifically, the SLIC algorithms.md, in my opinion, suffered severely since the algorithm was shown to be obviously less effective than connected components early on in both the 2D and the 3D cases. I sensed that Will was frustrated with spending so much time performing analysis on an algorithm that would not be used in our pipeline.

Finally, as I have continued working on the algorithms.md for both the PLOS (redoing it in the correct format) and for NDReg, I have found that the most difficult section for me is, undoubtedly, evaluating the effectiveness on the real world data. As you know, or team has little to no 'truth' for our data other than a vague notion of density and synapse volume, so measuring success of a pipeline is quite difficult. Personally, I had trouble grasping the intuition behind the discriminability metric, and was unsure how to bridge the gap from the (very loose) theoretical understanding that I had to the specific implementation I needed for our data in a meaningful way. If other students feel this way, it may be worth running a class on methods for evaluating  pipelines on data without many prior knowns.

**Comment by levinwil** [comment]
Pros: 

Algorithms.md was useful in that it helped us completely understand the algorithms that we were using in our pipeline, and the algorithms we were thinking about implementing. Because we had to go into such detail about nearly every aspect (I will address why I say "nearly" in the improvements section), I was able to identify, diagnose, and explain why we got results that we did not expect. As a result, I was able to go back and refine our algorithm to perform as expected, or to determine if the algorithm isn't immediately applicable to our project. 

Cons: 

I think that Algorithms.md's Simulation Data Analysis section was a bit restrictive in terms of its effectiveness metrics. Specifically, it required qualitative and quantitative data metrics when such measures don't always have very much meaning. In certain circumstances, I would say to leave it up to the writer how he/she would like to determine if the algorithm was effective, and how effective it was. 

I would also say that Algorithms.md's greatest strength can also be seen as its greatest weakness. Because Algorithms.md gives you a greater understanding of the algorithm (specifically the pseudocode section), it also immediately tells you if the algorithm will or will not be applicable to your project. Thus, you know early on if you will or will not use it at all. In the case that you know you will not implement that algorithm, I'm not sure a created full-fledged Algorithms.md is always effective. 

Improvements:

I think it would be very helpful to have an overview section at the very beginning where the user outlines what the algorithm actually does, its inputs, its outputs, any special requirements, and the pseudocode. I think it would be a really good idea to "quiz" the user on what they think it does and how to implement it, have them go through imperfect and perfect simulation data, and then get a "grade" (i.e. data metric) on how well they know that algorithm. That way, if the data metrics after the simulation data turn out to deviate from expectation, they know they should go back and research the details of the algorithm (this is assuming there were no errors in generating the simulation data)

**Comment by rguo123** [comment]
Pros:
Algorithms.md was extremely helpful for me especially since I joined the pan-synapse research project late. I believe the easy and difficult simulation and the pseudocode aspects really helped me understand how exactly the algorithms we implemented worked and their limitations. Even though the simulation analysis was tedious, I found that having data where I knew what the outputs "should be" helped me understand exactly how my data was being processed by the algorithm. 

Cons:
My main concern with algorithms.md is very similar with the others. The assignment can be time-consuming and might not be effective for algorithms that we know for certain will not work. 

Improvements: 
This comment was submitted late. The new algorithms.md already addresses many of the concerns mentioned above. I will update this further after writing an algorithms.md in the new format. For now, I think it would be helpful to have a reflection at the end of real data analysis. This reflection should include potential steps that should be made to improve the algorithm or data pre-algorithm processing (so the data runs better in the algorithm).

**Comment by jonl1096** [comment]
Yeah I like the re-addition of the pseudocode to the top of Algorithms.md and overall I think the logical progression from understanding->simulation->real data is more intuitive now as well.  Overall, I agree with Tanay and Nitin in how the assumed time is definitely longer than 10 hours, at least for this first week, but I do think as we get more used to the process about 10 is a good estimate, just because so much time this week was spent understanding what exactly was wanted and what determining discriminability required.    Also perhaps requiring a table of contents so that other readers can quickly control-f each section might be helpful, just because I found myself getting lost a lot within my notebooks just because they were so long.  But then again that might also just be a personal issue.  In the end I think Algorithms.md is at a good place right now.

**Comment by jovo** [comment]
@levinwil thanks for your feedback, very helpful.  in terms of:
```
In certain circumstances, I would say to leave it up to the writer how he/she would like to determine if the algorithm was effective, and how effective it was.
```

agreed, the developer can choose, but your job is to convince other people that it will run on *their* data.  they should *not* believe you unless you can show them qualitative demonstrations that it works, because summary statistics will always be just that, meaning that they discard lots of information.  the next question they will ask is: but is it better than Algorithm X.  it is also the next question we will ask.  thus, quantitative metrics are also *always* required.  lots of people have successfully convinced themselves by looking at pictures that their algorithm was working great.  but, pictures can be misleading, algorithms should optimize something, so it is important to determine what it is that we are optimizing, so that we can fine tune it for that.

**Comment by jovo** [comment]
@rguo123 i am adding a reflections bit at the end
@jonl1096 great, looking forward to more feedback next week.
